### ISSUE TITLE
Firefox fails to build

### ISSUE THREAD

**Issue by LennartRoeder** [joscha/prime-ratings#3]
When building the FF version, grunt fails. It doesn't matter, if it is in dev or dist version. Even forcing does not produce the desired result.

```
$ grunt ff:dist --force
(node:31564) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Running "copy:ff" (copy) task
Created 2 directories, copied 10 files

Running "mozilla-cfx-xpi:stable" (mozilla-cfx-xpi) task
Creating dist dir '/home/lennart/git/prime-ratings/dist/firefox'...
Creating xpi...
Warning: There was an error running mozilla-cfx-xpi. Error: Traceback (most recent call last):
  File "/home/lennart/git/prime-ratings/tmp/mozilla-addon-sdk/addon-sdk-1.17-official/bin/cfx", line 30, in <module>
    import cuddlefish
  File "/home/lennart/git/prime-ratings/tmp/mozilla-addon-sdk/addon-sdk-1.17-official/python-lib/cuddlefish/__init__.py", line 381
    except SystemExit, e:
                     ^
SyntaxError: invalid syntax Used --force, continuing.

Done, but with warnings.
```

**Comment by joscha** [comment]
did you run `grunt setup` before?

**Comment by LennartRoeder** [comment]
yes, but it says:

```
grunt setup
(node:32558) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Running "mozilla-addon-sdk:stable" (mozilla-addon-sdk) task
Mozilla Addon SDK already downloaded
```

**Comment by joscha** [comment]
seems to work locally for me, but I had all extensions already installed.

**Comment by LennartRoeder** [comment]
the readme of the addon-sdk says:

> Note that Python 3 is not supported.

```
 ~  python --version
Python 3.5.2
  ~  python2 --version
Python 2.7.12
```

I probably need it to tell to use python2 instead of python

**Comment by joscha** [comment]
don't worry about it, I just found out that FF does not accept add-ons built with cfx any more - I won't update the FF version.

**Comment by Gitoffthelawn** [comment]
Perhaps the WebExtensions version will work on Firefox since it now officially supports much of WebExtensions.

**Comment by joscha** [comment]
Most likely, would you like to transform it? I am happy to merge a PR!

**Comment by Gitoffthelawn** [comment]
@joscha I wish I had the time, but I am overbooked right now!  Perhaps someone else can work on it.
